### ISSUE TITLE
Docker: rails db:migrate step failing

### ISSUE THREAD

**Issue by livingfreely** [standardnotes/syncing-server#11]
Hello,

first off, I'm not familiar with ruby or rails.
I tried getting the docker container up and running with docker-compose and also with docker build. I'm facing the issue that the build process fails at Step 10/11 which is `RUN rails db:migrate`. I'm getting the Error `/bin/sh: 1: rails: not found`. 
Now I checked the mentioned requirements and installed them. I am on a Debian distribution and I tried installing ruby and rails using apt but also using rvm with the referenced versions.
I launched /bin/sh and tried running the command and it is working. But when I try building with docker I still get the Error.

I'm sure I'm missing something really stupid here but since I can't find any more to go on googling I need to ask here.

Any help is appreciated.

**Comment by livingfreely** [comment]
I managed to find a workaround now. Replacing the `rails` command in Dockerfile / docker-compose.yml with `./bin/rails` did the trick. I am not sure if this is the intended way though.

**Comment by joekerna** [comment]
I can confirm the issue and the workaround above

**Comment by mobitar** [comment]
cc @mindovermiles262

**Comment by mindovermiles262** [comment]
I’ll take a look at this today. Thanks for pinning me

**Comment by johnny243** [comment]
Since the gems are installed with bundler with `bundle install`, the `rails` command will not be available. We should use `bundle exec rails` instead.

If for some reason one would still need the `rails` command, run `gem install rails` within the `Dockerfile` and the `rails` command will be available for use.

**Comment by livingfreely** [comment]
Great work @johnny243 it seems you have good knowledge about this topic. Thank you
