### ISSUE TITLE
Storing mysql root password is bad and not needed

### ISSUE THREAD

**Issue by tuxick** [standardnotes/syncing-server#113]
I noticed DB_ROOT_PASSWORD used in .env file. This is always a bad idea, and `bundle exec rails db:create db:migrate` will prompt for password anyway.

**Comment by JaspalSuri** [comment]
Hi @tuxick,

I've assigned this thread to our back-end devs and they will get in touch with you. Thank you for your feedback!

**Comment by karolsojko** [comment]
This is only used for local development and is a required parameter for running MySQL container in `docker-compose` setup, see: https://hub.docker.com/_/mysql

You don't have to set up the variable if you are running from a pre-built official image

**Comment by tuxick** [comment]
So adding a comment in the env sample should be enough, i suppose.
