### ISSUE TITLE
HTTP parse error with nginx reverse proxy

### ISSUE THREAD

**Issue by 0lzi** [standardnotes/syncing-server#127]
Im using the syncing server on a raspberry pi, i have nginx setup for reverse proxy on another machine.

here is my nginx proxy config

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name notes.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

 location / {

 include /config/nginx/proxy.conf;
 proxy_pass http://192.168.1.16:3000; # IP of Raspberry pi

  }

}

```

when i navigate to ```192.168.1.16:300``` locally i get

![image](https://user-images.githubusercontent.com/4409144/96574584-8b500080-12c7-11eb-854e-ee3bdf321a00.png)
 
which i expect, but navigating to my subdomain  notes.domain.com and get this in the logs

`I, [2020-10-20T10:07:58.977927 #73]  INFO -- : {"method":"GET","path":"/","format":"html","controller":"ApplicationController","action":"home","status":200,"duration":1.68,"view":0.89,"dd":{"trace_id":"0","span_id":"0","env":"","service":"","version":""},"ddsource":["ruby"],"time":3939.59427887,"params":{"controller":"application","action":"home"},"level":"INFO"}`

I get

![image](https://user-images.githubusercontent.com/4409144/96574661-a91d6580-12c7-11eb-9924-2299ae6d11d7.png)

here are the logs for this

`2020-10-20 10:21:53 +0000 HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>`

all other services that use http or https work with this set up and a prox_pass the IP and port and it works fine, so not sure whats happening here.

**Comment by johnny243** [comment]
Hey @0lzi 

It looks like `nginx` is trying to access `https://192.168.1.16:3000` which is not valid since the `puma` server is in non-SSL mode. I would start by adjusting the `.conf` file a bit:

```
upstream backend {
        server 192.168.1.16:3000;
}

server {
        server_name your-domain;
        rewrite ^(.*) https://your-domain$1 permanent;
}

server {
        listen                  443 ssl;
        ssl_certificate         /etc/ssl/certs/nginx.crt;
        ssl_certificate_key     /etc/ssl/private/nginx.key;
        keepalive_timeout       70;
        server_name             your-domain;

        location / {
                proxy_pass http://backend;
        }
}
```

Replace `your-domain` with your real domain.

And adjust `ssl_certificate` and `ssl_certificate_key` as necessary.

Let me know if this helps!

**Comment by 0lzi** [comment]
Thanks for the reply @johnny243 

bit more background, im using the [Linuxserver.io SWAG](https://docs.linuxserver.io/general/swag) image for the reverse proxy.

I am then just editing the proxy-conf files to proxy_pass to where i need, and it works for everything i have tried so far minus this.

Will keep digging, and will update and close if i sort it.

thanks
