### ISSUE TITLE
Yarn executable was not detected in the system

### ISSUE THREAD

**Issue by iganeshk** [standardnotes/syncing-server#13]
Trying to setup StandardNotes with docker platform following the instructions form https://docs.standardnotes.org/self-hosting/self-hosting-with-docker

While attempting to execute the app by running 
`$ docker-compose exec app bundle exec rake assets:precompile`

I get 
```
Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install
```
Host system has yarn but I'm unaware of the docker build.

-------
OS: Debian 10
Docker: Docker version 19.03.5, build 633a0ea838
Docker-Compose: docker-compose version 1.25.1, build a82fef07

**Comment by johnny243** [comment]
Hi @iganeshk, sorry you are having this issue. Could you please try this guide instead? https://github.com/standardnotes/syncing-server#docker-compose

**Comment by iganeshk** [comment]
Hey @johnny243! So I was able to get it up and running. I do happen to have one issue, I followed https://github.com/standardfile/ruby-server/issues/74 to disable new registration, it worked fine upon restarting with passenger-config. What would be the best way to restart/reload on docker container?

I tried `docker-compose up -d --no-deps --build app` after stopping the app, but no avail.

**Comment by iganeshk** [comment]
Figured it out for now by build it with no-cache
`docker-compose build --no-cache app`
