### ISSUE TITLE
how to remember login status, always ask me for login when I open the android app

### ISSUE THREAD

**Issue by ijustyce** [standardnotes/syncing-server#143]
First of all, thanks for your great work, But I face some issue and need your help.

I use self hosted version, but always ask me for login even if  I was logged in before. Both the web app and the android app has this issue. Can you help me fix it. My server run on the raspberry pi 4

**Comment by JaspalSuri** [comment]
Hi @ijustyce,

What is your current self-hosting setup (i.e. are you using Docker with the Pi)? Do you have access to any error logs that might help us investigate further?

**Comment by ijustyce** [comment]
Hi @JaspalSuri ,
I run with docker on raspberry pi 4 and it will ask me to re-enter email and password if I re-open the android app after close it for a while.
I typed `docker logs -f --since 1m xxx`  then re-open the android app and it asked me to re-enter email and password again. Below is the output logs.
`{"level":"DEBUG","time":"2020-11-27T03:01:53.314+00:00","message":"   (0.9ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 180","ddsource":["ruby"]}
{"level":"DEBUG","time":"2020-11-27T03:01:53.318+00:00","message":"  Session Load (1.7ms)  SELECT  `sessions`.* FROM `sessions` WHERE `sessions`.`uuid` = 'xxx' LIMIT 1","ddsource":["ruby"]}
{"level":"DEBUG","time":"2020-11-27T03:01:53.324+00:00","message":"  User Load (1.5ms)  SELECT  `users`.* FROM `users` WHERE `users`.`uuid` = 'xxx' LIMIT 1","ddsource":["ruby"]}
{"level":"INFO","time":"2020-11-27T03:01:53.328+00:00","message":"{\"method\":\"POST\",\"path\":\"/items/sync\",\"format\":\"html\",\"controller\":\"Api::ItemsController\",\"action\":\"sync\",\"status\":401,\"duration\":17.42,\"view\":0.63,\"db\":4.07,\"dd\":{\"trace_id\":\"0\",\"span_id\":\"0\",\"env\":\"\",\"service\":\"\",\"version\":\"\"},\"ddsource\":[\"ruby\"],\"time\":25287.591002005,\"params\":{\"items\":\"[FILTERED]\",\"sync_token\":\"xx=\\n\",\"compute_integrity\":false,\"limit\":150,\"api\":\"20200115\",\"controller\":\"api/items\",\"action\":\"sync\",\"item\":{}},\"level\":\"WARN\"}","ddsource":["ruby"]}`

Here is the screenshot of android app.
![微信图片_20201127131938](https://user-images.githubusercontent.com/6041166/100413817-374cee80-30b3-11eb-889b-b6cec48ec42a.jpg)

**Comment by karolsojko** [comment]
Hi @ijustyce ,

- are you using the `stable` or the `latest` version of Docker image?
- what value do you have in your env file regarding `RAILS_ENV`? 

I have a feeling that your issue might be related to short-lived sessions in development mode, see: https://github.com/standardnotes/syncing-server/blob/develop/config/sn_session.yml

**Comment by mrichtsfeld** [comment]
@karolsojko I initially used "development" and switched to "production" later. Regarding Docker I used the `stable` version. Is there anything else I need to do except `docker-compose restart` for the new `RAILS_ENV` to become active?

**Comment by karolsojko** [comment]
- `RAILS_ENV=production` will allow you for a longer lived session
- `standardnotes/syncing-server:stable` is the recommended Docker image since `latest` is always in a "work-in-progress" state.

`docker-compose restart` won't do. After [Docker docs](https://docs.docker.com/compose/reference/restart/):
```
For example, changes to environment variables (which are added after a container is built, but before the container’s command is executed) are not updated after restarting.
```

I would suggest killing the containers and starting the up again. That should do the trick.

**Comment by ijustyce** [comment]
@karolsojko thanks, the value of `RAILS_ENV` is development. The offical docker image keep restart on pi4, so I build my own docker image.

**Comment by mrichtsfeld** [comment]
@karolsojko that helped for me. I have updated the description in the .env.sample file and the documentation and created a pull request. Should be clearer now. Thanks for your help.

**Comment by ijustyce** [comment]
@karolsojko thanks again, now work fine.
