### ISSUE TITLE
Version 004 / Sync Client v3.5

### ISSUE THREAD

**Issue by pixel2920** [standardnotes/syncing-server#145]
If my syncing-server is on the current `master` branch (as of today), should I have gotten a prompt to upgrade to encryption version 004, or is that still on `develop`?

**Comment by baptiste-grob** [comment]
Hey @pixel2920, the encryption upgrade prompt is disabled in all versions of the apps at the moment, and we'll enable it sometime in early 2021.

**Comment by karolsojko** [comment]
I think we can mark this as resolved - please feel free to reopen if needed
