### ISSUE TITLE
ARM64 version

### ISSUE THREAD

**Issue by maaroen** [standardnotes/syncing-server#146]
Hello,

Would it be possible for you to upload next to the AMD64 and ARM64 version/ to DockerHub?

I would like to run this image in a k8s cluster on my Raspberry Pi, so an ARM64 image would be handy so I don't have to build it myself.

Kind regards,

Maaroen

**Comment by karolsojko** [comment]
Good idea @maaroen - putting on my to-do list

**Comment by maaroen** [comment]
@karolsojko I could provide you the docker commands if you want.

**Comment by karolsojko** [comment]
@maaroen feel free to open a pull request :)

**Comment by karolsojko** [comment]
Happy Holidays 🎅 🎄 !

We now publish the ARM64 version of the Docker image: https://hub.docker.com/r/standardnotes/syncing-server/tags?page=1&ordering=last_updated

@maaroen can you confirm it works for you?
