### ISSUE TITLE
PostgreSQL support?

### ISSUE THREAD

**Issue by cr0ssmind** [standardnotes/syncing-server#154]
Are you planning support PostgreSQL too in the future?

**Comment by JaspalSuri** [comment]
I'm not currently aware of any plans to to support PostgreSQL in the near future.

**Comment by karolsojko** [comment]
Currently no - future development is made in https://github.com/standardnotes/syncing-server-js 

The list of future priorities at the current moment holds us from implementing new db drivers

**Comment by cr0ssmind** [comment]
It's (sadly) clear, thank you for the answer! Keep the great work!
