### ISSUE TITLE
docker-compose up -d

### ISSUE THREAD

**Issue by serverfilesync** [standardnotes/syncing-server#163]
Helllo,

I follow the docker instruction using docker-compose in Debian. Except that I changed the volume bind mount path in the docker-compose.

However, I am getting the below error:

ERROR: for app  Cannot start service app: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "docker/entrypoint.sh": stat docker/entrypoint.sh: no such file or directory: unknown

ERROR: Encountered errors while bringing up the project.

Any idea what is going on? I've check the folder permissions and they should be all clear. Thanks!

**Comment by karolsojko** [comment]
@serverfilesync if you look at the entrypoint of the Docker image it is defined like this: https://github.com/standardnotes/syncing-server/blob/develop/Dockerfile#L28

So what I can read from the error you supplied is that you don't have the sources properly mounted as a volume to the image. The `entrypoint.sh` file needs to be mounted at `/syncing-server/docker/entrypoint.sh` in order for the image to work.

**Comment by karolsojko** [comment]
Closing this one. Feel free to reopen if needed
