### ISSUE TITLE
[Help Wanted] bundler: failed to load command: rake

### ISSUE THREAD

**Issue by kushfest** [standardnotes/syncing-server#167]
**Describe the issue**
I've been using standardnotes for some time without issue, but after updating today (pulled the latest docker image and ran git pull on the syncing-server folder), I'm finding my server at a standstill. It gets stuck when starting, which renders it unusable. This is what repeats in my logs when I start the syncing-server in docker:

```
bundler: failed to load command: rake (/usr/local/bundle/bin/rake),
Prestart Step 1/3 - Removing server lock,
Prestart Step 2/3 - Migrating database,
	from /usr/local/bundle/bin/bundle:23:in `<main>',
/usr/local/bundle/gems/bundler-2.2.5/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find racc-1.5.2 in any of the sources (Bundler::GemNotFound),
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/spec_set.rb:81:in `map!',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/spec_set.rb:81:in `materialize',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/definition.rb:245:in `specs_for',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/runtime.rb:91:in `block in definition_method',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/definition.rb:175:in `specs',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/definition.rb:227:in `requested_specs',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/runtime.rb:20:in `setup',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler.rb:148:in `setup',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/setup.rb:20:in `block in <top (required)>',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/ui/shell.rb:88:in `silence',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/setup.rb:20:in `<top (required)>',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/ui/shell.rb:136:in `with_level',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/cli/exec.rb:61:in `kernel_load',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/cli/exec.rb:61:in `require_relative',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/cli/exec.rb:28:in `run',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/cli.rb:494:in `exec',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/cli.rb:30:in `dispatch',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/cli.rb:24:in `start',
	from /usr/local/bundle/gems/bundler-2.2.5/exe/bundle:49:in `block in <top (required)>',
	from /usr/local/bundle/gems/bundler-2.2.5/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors',
	from /usr/local/bundle/gems/bundler-2.2.5/exe/bundle:37:in `<top (required)>',
	from /usr/local/bundle/bin/bundle:23:in `load'
```

I tried starting with a fresh syncing-server folder cloned from github and a new pull of the "standardnotes/syncing-server:latest" docker image but the result was the same. I also tried the "standardnotes/syncing-server:stable" docker image, but that didn't seem to change anything either. 

I'd love to get my standardnotes server back online ASAP. Any suggestions?

**Expected behavior**
Typically it just boots up and works hah.

**Desktop (please complete the following information):**
 - OS: Docker on Ubuntu 18

**Comment by karolsojko** [comment]
Hi @kushfest we've announced on our Slack that we're deprecating `stable` tag and using `latest` instead to represent the state that is on production. 

`dev` is the version that we have a work-in-progress state so please use at your own risk. 

Recommended tag: `latest`

**Comment by kushfest** [comment]
Thanks for this answer. I'd love to make the move back to the 'latest' tag, but I'm getting the same error I originally posted about when I try to do that. If I go back to the dev branch things seem to go back to functional. Any suggestions on how to migrate back? I tried cloning the git repo fresh and updating the .env file, but I'm having that same issue where it just never gets past migrating database.
