### ISSUE TITLE
"Unknown Error" when connecting to raspberry pi syncing-server

### ISSUE THREAD

**Issue by miroesli** [standardnotes/syncing-server#172]
# Syncing Server Unknown Error
When trying to connect to the server, it will pop-up with “Unknown Error”.
## Requirements
-	Raspberry pi running on Raspbian 
-	Architecture: Armv7 / armhf
-	Raspberry Pi already setup with pi-hole using lighttpd web server
## Setup Process
Below is what steps I did to achieve the “Unknown Error” and what else I tried.
### Raspberry Pi Docker with Configured `.env` file

-	Followed instructions on the [docs page for raspberry pi](https://docs.standardnotes.org/self-hosting/raspberry-pi/). Below is the `.env` file configuration. The `SECRET_KEY_BASE` and `PSEUDO_KEY_PARAMS_KEY` are replaced with the same output from `openssl rand -hex 64`. 

``` .env
# Sample ENV setup Variables
# Copy this file and update as needed.
#
#   $ cp .env.sample .env
#
# Do not include this new file in source control
#

# Rails Settings
EXPOSED_PORT=3000
# change this to "production" for production use, otherwise the access token time is very short and forces re-login
RAILS_ENV=production
RAILS_LOG_TO_STDOUT=false
# Log Level options: "INFO" | "DEBUG" | "INFO" | "WARN" | "ERROR" | "FATAL"
RAILS_LOG_LEVEL=INFO
#SQS_QUEUE=somequeue
#SQS_QUEUE_LOW_PRIORITY=low_priority_queue
#AWS_REGION=us-west1
#S3_BACKUP_BUCKET_NAME=

ACTIVE_JOB_QUEUE_ADAPTER=async

# Database Settings
DB_PORT=3306
DB_HOST=127.0.0.1
DB_DATABASE=standard_notes_db
DB_USERNAME=std_notes_user
# Please change this!
DB_PASSWORD=T3st1ng
DB_POOL_SIZE=30
DB_WAIT_TIMEOUT=180

# Secrets
# Use: "bundle exec rake secret" or "openssl rand -hex 64"
# To generate required secret key base below

SECRET_KEY_BASE=KEY1
PSEUDO_KEY_PARAMS_KEY=KEY1

# Disable user registration
#DISABLE_USER_REGISTRATION=true

# Datadog
DATADOG_ENABLED=false

# Mailer settings
SMTP_HOST=
SMTP_PORT=
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_DOMAIN=
EMAIL_ATTACHMENT_MAX_SIZE=10485760

# SNS EVENTS
#SNS_TOPIC_ARN=

# (Optional) Database Replication
#DB_REPLICA_HOST=

# Revisions persistency
REVISIONS_FREQUENCY=300

# (Optional) Redis Cache for ephemeral sessions
#REDIS_URL=redis://cache:6379
```
-	Then ran the command `sudo docker-compose -f docker-compose.yml -f docker-compose.raspberry-pi.yml up -d`
-	Output from `curl ip-of-raspberry-pi:3000` is `{"message":"Hi! You're not supposed to be here."}` . Same result using both public and local ip. This shows that the server is running on the right port, is port forwarded correctly, and I am using the right IP.
-	Attempt to register an account using `ip-of-raspberry-pi:3000` as sync server domain
-	Popup of Unknown Error
 
![image](https://user-images.githubusercontent.com/17695280/105912863-ebe68c00-5fe0-11eb-9c2b-f4853d7cb87a.png)

-	Stopped docker containers and removed them using ` sudo docker stop syncing-server_app_1 syncing-server_cache_1 syncing-server_db_1 && sudo docker rm syncing-server_app_1 syncing-server_cache_1 syncing-server_db_1` and then tried with different keys but still get the same result.
#### Note
-	Sometimes app container keeps restarting when attempting to start using previous docker command. Checked issues #27 and #93 but nothing from there seemed to help.
 
![image](https://user-images.githubusercontent.com/17695280/105912945-0456a680-5fe1-11eb-9817-02430ea3c6c2.png)
![image](https://user-images.githubusercontent.com/17695280/105912955-0882c400-5fe1-11eb-8477-ca7960a590db.png)

-	Attempted to run without configuring the .env after copying the .env.sample file and it was able to run without restarting but resulted in the same “Unknown Error”
-	My guess is that when changing the DB_PASSWORD, it is not able to startup the app correctly. Perhaps I am supposed to change the DB password in sql somehow? There were no instructions on how to do this or if we should do this though.
### Instructions from README using ruby on rails
-	Followed docker but it seemed that mysql doesn’t support raspberry buster – attempted to install the Debian buster version, but said it doesn’t support armhf
### Instructions from README using Docker
-	Then When following [docker setup from the Github README]( https://github.com/standardnotes/syncing-server#docker-setup), it does not find the matching manifest when pulling the standardnotes/syncing-server Docker Hub image. I used the command `docker pull standardnotes/syncing-server`. If this had worked I would have then executed `sudo docker run -d -p 3000:3000` --env-file=.env standardnotes/syncing-server

![image](https://user-images.githubusercontent.com/17695280/105912995-159fb300-5fe1-11eb-9570-33cbd468071e.png)
 
### Instructions using Docker from Standardnotes help page
-	Ran `sudo docker-compose up -d` as it shows at the end of the [docker setup docs page]( https://docs.standardnotes.org/self-hosting/docker/) but said it couldn’t find matching manifest for linux/arm/v7 as before. This shows that I need to follow the docker instructions for the raspberry pi version specifically.

![image](https://user-images.githubusercontent.com/17695280/105913034-23553880-5fe1-11eb-8c4d-1ebacb66b185.png)

### Other things I’ve tried
-	Setting up a domain to check if it didn’t like that I was redirecting through a port forwarded IP
-	Followed article () to check if it didn’t like having the syncing server on HTTP instead of HTTPS but nginx wasn’t very compatible with the web server from pi-hole. One developer in the slack channel said that HTTPS wasn’t necessary to run though.
-	Future tests could include trying to install mysql on raspberry pi and test with using ruby on rails installation though I can’t see it working since it probably doesn’t support raspberry pi and there were changes needed to support raspberry pi.

**Comment by mobitar** [comment]
Are you using the web app or desktop app to sign into your server? Our official web app requires a HTTPS domain, so you should try the desktop app, then also open the Network inspector (via Chromium dev tools) in the app to see what it's reporting.

**Comment by miroesli** [comment]
@mobitar Yep, seems that was the case! Was able to login fine on the desktop app. I do have a couple questions though:

1. how would I setup HTTPS without NGINX? I tried following the [documentation on securing your HTTP trafic](https://docs.standardnotes.org/self-hosting/https-support), but my pihole server hosts its webserver on port 80. Additionally, replacing pihole's lighttpd webserver with NGINX didn't seem to let me visit the pages anymore. 
2. Why is it that I can only host the server on raspberry pi when the password isn't changed from the default changeme123?

**Comment by mobitar** [comment]
Not sure about number 2. Would need more info. Make sure your ENV is set to production and not development.

**Comment by netstx** [comment]
I essentially had the same issue as @miroesli when following instructions from https://docs.standardnotes.org/self-hosting/docker/

**Comment by karolsojko** [comment]
Unfortunately, those docs are outdated and we're working on new infra and updating those docs as we speak.

We plan to update the self-hosting docs for Docker in the future to help provide a more seamless setup experience for everyone. Please follow our repo changes for updates.

**Comment by netstx** [comment]
Thanks for the update @karolsojko - I spent a couple of hours trying to get the syncing server running on docker, to see if I could find the issue, and no luck, otherwise I'd share some news here. The web app docker ran just fine. I will keep an eye out, thank you.

**Comment by karolsojko** [comment]
@netstx we've updated our setup Today - can you update your local code to the latest and check the updated README to see if that works for you?

**Comment by netstx** [comment]
@karolsojko I cloned the master branch, ran the server.sh commands and everything came up. When trying to register, I get the following message: Your credentials are needed to refresh your session with the server. Then after entering the username and password I just created, I get "Update Recommended. The encryption version for your account is outdated...". I use these brand new credentials and get "Invalid authentication. Please try again.".

**Comment by netstx** [comment]
Here are some additional logs:

```
syncing-server_1            | {"level":"INFO","time":"2021-03-01T14:57:21.156+00:00","message":"{\"method\":\"GET\",\"path\":\"/auth/params\",\"format\":\"json\",\"controller\":\"Api::AuthController\",\"action\":\"auth_params\",\"status\":500,\"error\":\"ActiveRecord::StatementInvalid: Mysql2::Error: Lost connection to MySQL server during query: SELECT  `users`.* FROM `users` WHERE `users`.`email` = 'rafaelpossa@gmail.com' LIMIT 1\",\"duration\":5.21,\"view\":0.0,\"db\":1.62,\"dd\":{\"trace_id\":\"0\",\"span_id\":\"0\",\"env\":\"\",\"service\":\"\",\"version\":\"\"},\"ddsource\":[\"ruby\"],\"time\":29712.307857538,\"params\":{\"email\":\"rafaelpossa@gmail.com\",\"api\":\"20200115\",\"controller\":\"api/auth\",\"action\":\"auth_params\",\"auth\":{}},\"level\":null}","ddsource":["ruby"]}
syncing-server_1            | {"level":"FATAL","time":"2021-03-01T14:57:21.158+00:00","message":"  ","ddsource":["ruby"]}
syncing-server_1            | {"level":"FATAL","time":"2021-03-01T14:57:21.158+00:00","message":"ActiveRecord::StatementInvalid (Mysql2::Error: Lost connection to MySQL server during query: SELECT  `users`.* FROM `users` WHERE `users`.`email` = 'rafaelpossa@gmail.com' LIMIT 1):","ddsource":["ruby"]}
syncing-server_1            | {"level":"FATAL","time":"2021-03-01T14:57:21.158+00:00","message":"  ","ddsource":["ruby"]}
syncing-server_1            | {"level":"FATAL","time":"2021-03-01T14:57:21.158+00:00","message":"app/controllers/api/auth_controller.rb:9:in `block in \u003cclass:AuthController\u003e'","ddsource":["ruby"]}
api-gateway_1               | {"message":"Could not pass the request to underlying services","level":"error"}
```

**Comment by karolsojko** [comment]
hmm might be related to #28 

I'll try to add one more command to the `server.sh` for cleaning up data. Might have to do with some previously initialised stuff.

**Comment by netstx** [comment]
Sounds good, thank you. Let me know if you'd like me to test anything else, I'd be happy to do it.

**Comment by karolsojko** [comment]
@netstx please update your code if you can and try doing `./server.sh cleanup` and then starting it once again. Let me know how it goes

**Comment by karolsojko** [comment]
Also keep in mind: I assumed you don’t have any pre-existing data so you are ok with wiping your data clean.

**Comment by netstx** [comment]
Looks like I am having the same issue, although the logs look a bit different.

```
syncing-server_1            | {"level":"WARN","time":"2021-03-01T16:16:27.165+00:00","message":"DEPRECATED: further development in https://github.com/standardnotes/syncing-server-js","ddsource":["ruby"]}
syncing-server_1            | {"level":"INFO","time":"2021-03-01T16:16:27.476+00:00","message":"Enqueued RegistrationJob (Job ID: 88e1cd1c-be62-45f8-8ec1-e6c23951e4a3) to Async(sn_main) with arguments: \"rafael@thinkpad.io\", \"2021-03-01 16:16:27 UTC\"","ddsource":["ruby"]}
syncing-server_1            | {"level":"INFO","time":"2021-03-01T16:16:27.477+00:00","message":"Performing RegistrationJob (Job ID: 88e1cd1c-be62-45f8-8ec1-e6c23951e4a3) from Async(sn_main) with arguments: \"rafael@thinkpad.io\", \"2021-03-01 16:16:27 UTC\"","ddsource":["ruby"]}
syncing-server_1            | {"level":"ERROR","time":"2021-03-01T16:16:27.493+00:00","message":"Error performing RegistrationJob (Job ID: 88e1cd1c-be62-45f8-8ec1-e6c23951e4a3) from Async(sn_main) in 12.72ms: NoMethodError (undefined method `request_uri' for #\u003cURI::Generic /admin/events/registration\u003e):\n/syncing-server/app/jobs/registration_job.rb:8:in `perform'\n/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/execution.rb:39:in `block in perform_now'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:109:in `block in run_callbacks'\n/usr/local/bundle/gems/i18n-1.8.5/lib/i18n.rb:313:in `with_locale'\n/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/translation.rb:9:in `block (2 levels) in \u003cmodule:Translation\u003e'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'\n/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/logging.rb:26:in `block (4 levels) in \u003cmodule:Logging\u003e'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'\n/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/logging.rb:25:in `block (3 levels) in \u003cmodule:Logging\u003e'\n/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/logging.rb:48:in `tag_logger'\n/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/logging.rb:22:in `block (2 levels) in \u003cmodule:Logging\u003e'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:136:in `run_callbacks'\n/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/execution.rb:38:in `perform_now'\n/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/execution.rb:24:in `block in execute'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:109:in `block in run_callbacks'\n/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/railtie.rb:28:in `block (4 levels) in \u003cclass:Railtie\u003e'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/execution_wrapper.rb:87:in `wrap'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/reloader.rb:73:in `block in wrap'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/execution_wrapper.rb:87:in `wrap'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/reloader.rb:72:in `wrap'\n/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/railtie.rb:27:in `block (3 levels) in \u003cclass:Railtie\u003e'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `instance_exec'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'\n/usr/local/bundle/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:136:in `run_callbacks'\n/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/execution.rb:22:in `execute'\n/usr/local/bundle/gems/activejob-5.2.4.4/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'\n/usr/local/bundle/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'\n/usr/local/bundle/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'\n/usr/local/bundle/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'\n/usr/local/bundle/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'\n/usr/local/bundle/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'\n/usr/local/bundle/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'","ddsource":["ruby"]}
syncing-server_1            | {"level":"INFO","time":"2021-03-01T16:16:27.524+00:00","message":"{\"method\":\"POST\",\"path\":\"/auth\",\"format\":\"json\",\"controller\":\"Api::AuthController\",\"action\":\"register\",\"status\":200,\"duration\":341.9,\"view\":1.11,\"db\":77.56,\"dd\":{\"trace_id\":\"0\",\"span_id\":\"0\",\"env\":\"\",\"service\":\"\",\"version\":\"\"},\"ddsource\":[\"ruby\"],\"time\":34458.294773013,\"params\":{\"password\":\"[FILTERED]\",\"email\":\"rafael@thinkpad.io\",\"ephemeral\":false,\"identifier\":\"rafael@thinkpad.io\",\"pw_nonce\":\"9f38413af313151fce8cef2b0efd10642a33f03e927e9d606906160e3c05921b\",\"version\":\"004\",\"origination\":\"registration\",\"created\":\"1614615386325\",\"api\":\"20200115\",\"controller\":\"api/auth\",\"action\":\"register\",\"auth\":{\"password\":\"[FILTERED]\",\"email\":\"rafael@thinkpad.io\",\"ephemeral\":false,\"identifier\":\"rafael@thinkpad.io\",\"pw_nonce\":\"9f38413af313151fce8cef2b0efd10642a33f03e927e9d606906160e3c05921b\",\"version\":\"004\",\"origination\":\"registration\",\"created\":\"1614615386325\",\"api\":\"20200115\"}},\"level\":\"INFO\"}","ddsource":["ruby"]}
```

Just to make sure, in the desktop app dvanced options (sync server domain) I am just adding "http://IP:3000". I verified it's reachable and get that "you're not supposed to be here" message.

**Comment by karolsojko** [comment]
@netstx this error actually gets us closer, so it's good - it should be fixed now so please update your code and try again if you can.

As for the http setup - you should be fine with what you have :)

**Comment by cherya** [comment]
@karolsojko  I'm had absolutely the same issue and your fix is worked for me!
But now I can't login to my server – generating login keys step is stuck (I am already tried mac os app and android app, and tried to restart and cleanup server)
<img width="243" alt="Screenshot 2021-03-02 at 12 04 01" src="https://user-images.githubusercontent.com/3810684/109624540-61e59200-7b4f-11eb-935f-8102570adb85.png">

**Comment by karolsojko** [comment]
@cherya thanks for the help - I've applied another [fix](https://github.com/standardnotes/api-gateway/commit/4a468d65c27c228e3dd6b149fedde0b10d798946). Can you try updating your code and doing `./server.sh update` afterwards ?

should fix that issue now

**Comment by cherya** [comment]
@karolsojko after `./server.sh update` it seems to work like a charm! Thank you 👍

**Comment by karolsojko** [comment]
@miroesli @netstx can you confirm this works for you as well?

**Comment by netstx** [comment]
@karolsojko I ran git pull, server cleanup then server update and start. Was able to register a new account using the desktop app. It's working now, thanks! Do you think it's "safe" to use it in production or should we keep testing it for a while still?

**Comment by karolsojko** [comment]
Although we're undergoing an infrastructure change we are taking all the precautions to make users satisfied. Your data and security is our highest priority :)

**Comment by karolsojko** [comment]
Closing this one in that case - feel free to reopen if the issue persists.

**Comment by netstx** [comment]
Thanks @karolsojko - appreciate all the help!

**Comment by netstx** [comment]
@karolsojko I wiped my original setup and started fresh since I plan on using it in production. I did git clone, server setup, server start and then server logs show the following:

```
syncing-server-js-worker_1  | nc: bad address 'syncing-server-js'
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
api-gateway_1               | nc: bad address 'syncing-server-js'
api-gateway_1               | syncing-server-js:3000 is unavailable - sleeping
syncing-server-js-worker_1  | nc: bad address 'syncing-server-js'
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
auth_1                      | nc: bad address 'syncing-server-js'
auth_1                      | syncing-server-js:3000 is unavailable - sleeping
api-gateway_1               | nc: bad address 'syncing-server-js'
api-gateway_1               | syncing-server-js:3000 is unavailable - sleeping
auth_1                      | nc: bad address 'syncing-server-js'
auth_1                      | syncing-server-js:3000 is unavailable - sleeping
syncing-server-js-worker_1  | nc: bad address 'syncing-server-js'
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
api-gateway_1               | nc: bad address 'syncing-server-js'
api-gateway_1               | syncing-server-js:3000 is unavailable - sleeping
syncing-server-js-worker_1  | nc: bad address 'syncing-server-js'
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
auth_1                      | nc: bad address 'syncing-server-js'
auth_1                      | syncing-server-js:3000 is unavailable - sleeping
api-gateway_1               | nc: bad address 'syncing-server-js'
api-gateway_1               | syncing-server-js:3000 is unavailable - sleeping
syncing-server-js-worker_1  | nc: bad address 'syncing-server-js'
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
auth_1                      | nc: bad address 'syncing-server-js'
auth_1                      | syncing-server-js:3000 is unavailable - sleeping
```

This is something that didn't happen earlier, any thoughts?

**Comment by miroesli** [comment]
@karolsojko Just tested with a fresh syncing-server. When following the setup as in the [README.md](https://github.com/standardnotes/syncing-server) I ended up having the following error after attempting to run `sudo ./server.sh start`.

```bash
ERROR: Service 'syncing-server' failed to build : failed to create endpoint unruffled_heyrovsky on network bridge: failed to add the host (veth3cb3065) <=> sandbox (veth9dd638b) pair interfaces: operation not supported
```

I tried to run `sudo ./server.sh update` which pulled some images but then resulted in the following while pulling from library/mysql.

```bash
ERROR: for db  no matching manifest for linux/arm/v7 in the manifest list entries
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

Here is the logs.

```bash
Attaching to syncing-server_cache_1
cache_1                     | 1:C 26 Jan 2021 22:22:50.194 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cache_1                     | 1:C 26 Jan 2021 22:22:50.194 # Redis version=6.0.10, bits=32, commit=00000000, modified=0, pid=1, just started
cache_1                     | 1:C 26 Jan 2021 22:22:50.194 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
cache_1                     | 1:M 26 Jan 2021 22:22:50.197 # Warning: 32 bit instance detected but no memory limit set. Setting 3 GB maxmemory limit with 'noeviction' policy now.
cache_1                     | 1:M 26 Jan 2021 22:22:50.198 * Running mode=standalone, port=6379.
cache_1                     | 1:M 26 Jan 2021 22:22:50.198 # Server initialized
cache_1                     | 1:M 26 Jan 2021 22:22:50.198 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
cache_1                     | 1:M 26 Jan 2021 22:22:50.199 * Loading RDB produced by version 6.0.10
cache_1                     | 1:M 26 Jan 2021 22:22:50.199 * RDB age 1325 seconds
cache_1                     | 1:M 26 Jan 2021 22:22:50.199 * RDB memory usage when created 0.63 Mb
cache_1                     | 1:M 26 Jan 2021 22:22:50.199 * DB loaded from disk: 0.000 seconds
cache_1                     | 1:M 26 Jan 2021 22:22:50.199 * Ready to accept connections
syncing-server_cache_1 exited with code 255
```
