### ISSUE TITLE
[Question] How can I see or check if Redis is working?

### ISSUE THREAD

**Issue by BobWs** [standardnotes/syncing-server#175]
Hi,
I was wondering how can I see or check if Redis is working with Syncing-server?

**Comment by karolsojko** [comment]
Are you running your setup with `docker-compose` ? If yes you can run commands like `docker-compose ps` to see the services running or `docker-compose logs -f` to monitor logs on the services

**Comment by BobWs** [comment]
> Are you running your setup with `docker-compose` ? If yes you can run commands like `docker-compose ps` to see the services running or `docker-compose logs -f` to monitor logs on the services

No I'm not running with docker-compose. I used Cli to install Standardnotes, and I'm using Portainer for monitoring and maintenance. So how can I see if Redis is working with Standardnotes?
The Redis container is running fine as far as I can see.

**Comment by karolsojko** [comment]
what do you have in mind by "is working with standardnotes" in particular?

**Comment by BobWs** [comment]
Well as I understand it redis works like a cache for Standardnotes. So this means that in the database of redis there should build the data. The file has to keep increasing in size at time as you use standardnotes with redis, thus I don't see this happening. I also don't see anything else in the logs of redis that indicates that it works with standardnotes. 

Or am I seeing it wrong?

**Comment by karolsojko** [comment]
Redis is used for temporarily caching data - like ephemeral sessions, login lock-outs etc

This data has a TTL so purges itself after a while. It's not stored in a permanent fashion. 

We use it in a few new features now so you might even not be using those at all

**Comment by karolsojko** [comment]
I hope this helps to understand the setup. Closing the issue - please reopen if needed
