### ISSUE TITLE
My iOS app keeps asking me for a password

### ISSUE THREAD

**Issue by SomaticFanatic** [standardnotes/syncing-server#179]
Hello. I’m taking notes via self hosting the syncing-server so let me know if maybe there’s a setting in here I can adjust.

Love Standard Notes but the iOS app I use to connect to my syncing server keeps prompting me for its password if I don't keep it open, and since it’s an app the password manager I use has no URL to use to autofind it, so I have to tediously search for the password every time I reopen the app.

I’ve tried disabling passcode, biometric FaceID, and local encryption on the iOS app but nothing stops this annoying password prompt.

Any ideas? I would prefer to just open the app to take notes without endlessly resubmitting my password.

**Comment by JaspalSuri** [comment]
Hi @SomaticFanatic,

Sorry to hear that. Please see this [comment](https://github.com/standardnotes/syncing-server/issues/143#issuecomment-737763083) for information on how to resolve this issue, and please let us know if you have any additional questions.

**Comment by SomaticFanatic** [comment]
I already use the RAILS_ENV:production variable. How do I switch to syncing-server:stable? Currently I’m just git cloning the repo and docker-compose up -d after setting up the yml and .env files.

**Comment by SomaticFanatic** [comment]
Ok I set the RAILS_ENV variable correctly and now it works. Thank you!

**Comment by JaspalSuri** [comment]
Hi @SomaticFanatic, 

I'm sorry that I wasn't there to answer your question earlier; I'm glad that you were able to figure it out! On Karol's behalf, you're very welcome. :)
