### ISSUE TITLE
IPv6 Support on hosted syncing-server

### ISSUE THREAD

**Issue by gordon-shumway-net** [standardnotes/syncing-server#18]
Hey together,
I hope this is the right repository for my question.
It seems that the hosted syncing-server sync.standardnotes.org on AWS is not support IPv6.
Is there any plan to support that in the future? :)

**Comment by mobitar** [comment]
Not something we have definite plans for currently, but perhaps something we'll explore at a later point.

**Comment by gordon-shumway-net** [comment]
Okay, thank you for your answer @mobitar , would be great to see that in the future!
