### ISSUE TITLE
Syncing server does not build, mimemagic version error

### ISSUE THREAD

**Issue by sparklyballs** [standardnotes/syncing-server#186]
when trying to build the docker images locally a new error has cropped up that prevents completion of the build.

```
Your bundle is locked to mimemagic (0.3.5), but that version could not be found
in any of the sources listed in your Gemfile. If you haven't changed sources,
that means the author of mimemagic (0.3.5) has removed it. You'll need to update
your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
in order to install.
The command '/bin/sh -c gem install bundler && bundle install' returned a non-zero code: 7
ERROR
````

I assume that it is related to this line in the gemfile.lock

https://github.com/standardnotes/syncing-server/blob/develop/Gemfile.lock#L135

**Comment by YesDrX** [comment]
to fix:
1. change mimemagic version in Gemfile.lock
    mimemagic (0.3.8)
      nokogiri (~> 1)
      rake (>= 0)
2. add shared-mime-info in Dockerfile before Run gen
    e.g.
    RUN apk --no-cache shared-mime-info
    RUN gem install bundler && bundle install

    note that shared-mime-info is dual licensed under the GNU-LGPL and AFL v2.0.

**Comment by giacco** [comment]
I had the same problem .
After chang mimemagic version in Gemfile.lock and installed shared-mime-info , I have successfully build the docker images.
Anyway it refused to start,

the server log says:
 ...
api-gateway_1               | nc: bad address 'syncing-server'
api-gateway_1               | syncing-server:3000 is unavailable - sleeping
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
...

why this errors appear?

**Comment by Svarto** [comment]
Same initial problem here. Fixed and got it all running with the below, as previously posted. Please note, @YesDrX  small typo in one of the commands, should be `RUN apk add --no-cache shared-mime-info`. I fixed it below.

> to fix:
> 
>     1. change mimemagic version in Gemfile.lock
>        mimemagic (0.3.8)
>        nokogiri (~> 1)
>        rake (>= 0)
> 
>     2. add shared-mime-info in Dockerfile before Run gen
>        e.g.
>        RUN apk add --no-cache shared-mime-info
>        RUN gem install bundler && bundle install
>        note that shared-mime-info is dual licensed under the GNU-LGPL and AFL v2.0.

@giacco it takes time until the DB is up. Also, depending on your settings some services seem to just quit if you haven't configured them. Ignore those logs and wait, after awhile the logs calm down and all is working and running. If you still are having issues, please open a new issue to keep this one on topic - thanks!

**Comment by PhoneMechanic** [comment]
I keep getting this error after versions in Gemfile.lock...  Your lockfile is unreadable. Run `rm Gemfile.lock` and then `bundle install` to
generate a new lockfile.
The command '/bin/sh -c gem install bundler && bundle install' returned a non-zero code: 20
ERROR: Service 'syncing-server' failed to build

**Comment by karolsojko** [comment]
To add some context to the discussion: https://www.theregister.com/2021/03/29/rails_mime_fix/

In the light of the above we'll be updating the syncing server to use Rails `5.2.5`

**Comment by sparklyballs** [comment]
> To add some context to the discussion: https://www.theregister.com/2021/03/29/rails_mime_fix/
> 
> In the light of the above we'll be updating the syncing server to use Rails `5.2.5`

What a mess.... 
Licensing is such a minefield

**Comment by karolsojko** [comment]
Fixed in https://github.com/standardnotes/syncing-server/commit/7acb912e1149144bf23930c269882198cffc7282

new Docker images published
