### ISSUE TITLE
docker-compose MySQL error

### ISSUE THREAD

**Issue by joekerna** [standardnotes/syncing-server#20]
I'm trying to run the server using `docker-compose`

My .env file is:

>   1 # Sample ENV setup Variables
  2 # Copy this file and update as needed.
  3 #
  4 #   $ cp env.sample .env
  5 #
  6 # Do not include this new file in source control
  7 #
  8 
  9 # Rails Settings
 10 EXPOSED_PORT=3000
 11 SECRET_KEY_BASE=changeme123
 12 RAILS_ENV=development
 13 #SQS_QUEUE=somequeue
 14 #AWS_REGION=us-west1
 15 
 16 # Database Settings
 17 DB_PORT=3306
 18 DB_HOST=127.0.0.1
 19 #DB_HOST=db #=> If using docker-compose
 20 
 21 DB_DATABASE=standard_notes_db
 22 DB_USERNAME=std_notes_user
 23 DB_PASSWORD=changeme123
 24 DB_ROOT_PASSWORD=changeme123

The container keeps restarting and the logfile says:

> app_1  | Mysql2::Error: Can't connect to MySQL server on '127.0.0.1' (107)

I'm especially unsure about lines 18/19 in the .env file. Can you please elaborate further?
Thanks a lot!

**Comment by joekerna** [comment]
#21 does not fix the issue for me. The Error remains

Is 
> DB_HOST=127.0.0.1

correct when using docker-compose?

Lines 18/19 are still confusing to me in .env

**Comment by johnny243** [comment]
@joekerna please use `DB_HOST=db` and then run `docker-compose up -d`

**Comment by joekerna** [comment]
Thanks,
Then I get

> Mysql2::Error: Access denied for user 'std_notes_user'@'172.31.0.3' (using password: YES)

I did replace 

> changeme123

with passwords of my choice. That's correct, right?

**Comment by johnny243** [comment]
That's correct.

If the issue persists, try removing the `std_notes_db` volume using the following command (assuming this is a new installation):

```
docker volume rm syncingserver_std_notes_db
```

And then run `docker-compose up -d`

**Comment by joekerna** [comment]
Awesome! It's working now!
Thanks a lot!
