### ISSUE TITLE
/var/lib/mysql does not exist

### ISSUE THREAD

**Issue by joekerna** [standardnotes/syncing-server#22]
I've successfully set up the syncing-server using `docker-compose`

The README states that the database will be written to `/var/lib/mysql`.

That directory does not exist on my server?!

`docker-compose.yml` is unchanged as

>  22     volumes:
 23       - std_notes_db:/var/lib/mysql

**Comment by johnny243** [comment]
It's most likely that you are looking at the wrong container :)

Please use: `docker ps` to get your `mysql` Container ID and then run `docker exec -it "<CONTAINER ID>" /bin/bash` to get an interactive shell. If you list `/var/lib/mysql`, it should be there.

**Comment by joekerna** [comment]
oh ok.. Thanks!
I though 

> Your MySQL Data will be written to your local disk 

means that it's stored outside the container.

If I backup that folder and restore it later, will all my users' notes be restored?

**Comment by johnny243** [comment]
Yeah, the statement seems to be somewhat confusing. We'll correct this. :)

As for the backup, you can do a full backup of `/var/lib/mysql` or use `mysqldump` to dump either option works.

**Comment by joekerna** [comment]
Great, thanks!
I'm now using:
```
SNOTES_DB_CONTAINER=$(/usr/bin/docker ps -a --filter "name=syncingserver_db_1" -q)
docker exec $SNOTES_DB_CONTAINER /usr/bin/mysqldump -u std_notes_user --password=changeme123 standard_notes_db > /backup/standardnotes_mysql.sql
```

It generates the MySQL dump. I'll try a test restore soon.

**Comment by joekerna** [comment]
Can you help me restore such a backup? Do I

1. clone
2. restore db
3. docker-compose ?

**Comment by karolsojko** [comment]
I think https://github.com/standardnotes/syncing-server/issues/90 sorts this out - @joekerna can you confirm?
