### ISSUE TITLE
Best way to upgrade selfhost from ruby-server?

### ISSUE THREAD

**Issue by pageb018** [standardnotes/syncing-server#23]
I am still using the "ruby-server" implementation of the Standard Notes server. Should I upgrade to the new "syncing-server" and if so, what is the best way to do this without losing notes.

**Comment by mobitar** [comment]
Updating is recommended, as you will no longer receive updates on the existing server. You shouldn't lose any notes. It should essentially involve just swapping out the ruby-server folder with the syncing-server folder, and it should work out of the box. But obviously first set it up side-by-side before making any destructive changes.
