### ISSUE TITLE
Using docker to host on my home-server

### ISSUE THREAD

**Issue by DanielAndreasen** [standardnotes/syncing-server#24]
Thanks for this interesting tool.
I'm trying to get this to run on my old laptop, which I use as a homeserver. I follow the instructions in the README:

```bash
$ git clone https://github.com/standardnotes/syncing-server/
$ cd syncing-server
$ cp env.sample .env  # And set DB_HOST=db. Everything else I leave as it is, even the "changeme123"
$ docker-compose up -d
```

Currently I'm at work, and can't easily reach my local network, however I ssh'ed into the server to run these commands, and when I do: `$ wget 192.168.0.100:3000`
I get the html below:

```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title> Standard File Server </title>
		<link rel="stylesheet" href="assets/home.css"/>
	</head>

	<body>
		<h1> Hi! You're not supposed to be here. </h1>

		<p> You might be looking for the <a href="https://app.standardnotes.org"> Standard Notes Web App</a> or the main <a href="https://standardnotes.org"> Standard Notes Website</a>. </p>
	</body>
</html>
```

Am I doing something wrong here? I'm also new to docker, so there might be something fundamental I don't understand.
Thanks for any help.

**Comment by bryvin** [comment]
This is actually correct and what you are meant to see. This typically means the app is started and running correctly.

You can see the same for Standard Note's hosted sync server here: https://sync.standardnotes.org/

**Comment by DanielAndreasen** [comment]
Alright, I guess I'm on the right path. If I want to host this entirely by myself, would I have to host the web component as well?

**Comment by bryvin** [comment]
Technically no. On the account sign in pop up you can click "Advanced Options" and change the "Sync Server Domain" but you would have to do that every time you signed in to your account.

I would also not suggest going that route as if we release any changes to the App, UI or structure of the syncing API you could be out of luck. So to keep everything together and on the same versioning I would suggest hosting your own copy of the web app as well. This way you can control when and what you update.

**Comment by DanielAndreasen** [comment]
Okay, thanks for all your help :)
