### ISSUE TITLE
Note History and Daily Email Backup

### ISSUE THREAD

**Issue by joshcsullivan** [standardnotes/syncing-server#26]
Today I set up the syncing server via docker-compose on a DigitalOcean VPS. Imported notes and syncing is working fantastic.

I do have a couple questions:

1. Note History - I can see the Session History of a note, but when I check the Note History Action Menu, it says there are no actions available, but the Note History Cloud link is installed. Does Note history not work on the syncing server?
2. Daily Email Backup - Is this not available in the syncing server?

Cheers,
Josh

**Comment by mobitar** [comment]
Note History is handled by a separate server that is non-self hostable, at least for now (too tightly coupled with other infrastructure). Email backups should work, but you'd have to have:

1. A job queue service
2. Proper SMTP settings configured

I believe you can modify the Rails job adapter to be in-memory, but I haven't done that in a while so you'll have to do some research there.

**Comment by joshcsullivan** [comment]
Thanks, @mobitar 

For now I'll stick with your sync solution then.
