### ISSUE TITLE
Can't register using domain name, working locally

### ISSUE THREAD

**Issue by Jungack** [standardnotes/syncing-server#29]
Hello,

I have problems setting up Standard Notes Syncing-Server. I am running Debian 10. Using a self-hosted web client, I am able to connect to my Syncing-Server using http://127.0.0.1:3000 (3000 being the port where is running the syncing-server when issuing `rails s -b=0.0.0.0 -p 3000`), but I can neither access It with http://domain.com nor https://domain.com. Trying to connect on [https://app.standardnotes.org/](https://app.standardnotes.org/) using https://domain.com also fails.

I think It must be a Passenger issue, but I don't know how to solve It. Indeed, when accessing http://127.0.0.1:3000 (3000 being the port where is running the syncing server when issuing `rails s -b=0.0.0.0 -p 3000`), I can see the page "You're not supposed to be here" with a normal presentation (Image 1). However, accessing the syncing server with http://domain.com or https://domain.com results in a page with "You're not supposed to be here" without any page layout (Image 2).

![Image 1](https://user-images.githubusercontent.com/57200786/74105444-23ed8880-4b5e-11ea-817a-68490e1d3c1d.png)
![Image 2](https://user-images.githubusercontent.com/57200786/74105445-24861f00-4b5e-11ea-8955-3ec86c10d632.png)

I have installed Ruby, RVM and Passenger using the official tutorial on Passenger website : [https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/ownserver/nginx/oss/stretch/install_passenger.html](https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/ownserver/nginx/oss/stretch/install_passenger.html).

Here are the logs when I try to access the syncing-server using http://domain.com or https://domain.com. The line 6 to 10 seems to be the main problem. :
```
^[[0;37m2020-02-09 16:38:19.906^[[0m [^[[32mINFO ^[[0m] Started GET "/" for **FILTERED** at 2020-02-09 16:38:19 +0100 (pid:776)
^[[0;37m2020-02-09 16:38:19.907^[[0m [^[[32mINFO ^[[0m] Processing by ApplicationController#home as HTML (pid:776)
^[[0;37m2020-02-09 16:38:19.908^[[0m [^[[32mINFO ^[[0m] Rendering application/home.html (pid:776)
^[[0;37m2020-02-09 16:38:19.908^[[0m [^[[32mINFO ^[[0m] Rendered application/home.html (0.1ms) (pid:776)
^[[0;37m2020-02-09 16:38:19.909^[[0m [^[[32mINFO ^[[0m] Completed 200 OK in 2ms (Views: 0.8ms) (pid:776)
^[[0;37m2020-02-09 16:38:19.964^[[0m [^[[32mINFO ^[[0m] Started GET "/assets/home.css" for **FILTERED** at 2020-02-09 16:38:19 +0100 (pid:776)
^[[0;37m2020-02-09 16:38:19.964^[[0m [^[[31mFATAL^[[0m]  (pid:776)
^[[0;37m2020-02-09 16:38:19.964^[[0m [^[[31mFATAL^[[0m] ActionController::RoutingError (No route matches [GET] "/assets/home.css"): (pid:776)
^[[0;37m2020-02-09 16:38:19.964^[[0m [^[[31mFATAL^[[0m]  (pid:776)
^[[0;37m2020-02-09 16:38:19.964^[[0m [^[[31mFATAL^[[0m] actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
rack (2.0.7) lib/rack/deflater.rb:34:in `call'
rack-cors (1.0.3) lib/rack/cors.rb:95:in `call'
secure_headers (6.1.1) lib/secure_headers/middleware.rb:11:in `call'
sentry-raven (2.12.0) lib/raven/integrations/rack.rb:51:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception' (pid:776)
```

My Standard notes config file for nginx is located in /etc/nginx/conf.d/standardnotes.conf all the other conf files for my other services and is the same as your tutorial : 
```
server {
    listen 443 ssl default_server;
    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;
    server_name domain.com;
    passenger_enabled on;
    passenger_app_env production;
    root /home/ec2-user/syncing-server/public;
  }
```

Please help me, I love this app and want to use It every day ! Thank you !

**Comment by Jungack** [comment]
Ok I have found that `rails assets:precompile` creates an `assets` EMPTY folder in `./syncing-server/public`. I am just following your tutorial on https://docs.standardnotes.org/self-hosting/ec2-nginx, without the command `bower install`.
Why is there anything when running `rails assets:precompile`? Issuing this command for the web client works like a charm, is it a bug in the syncing-server?

**Comment by johnny243** [comment]
Hey @Jungack, the message `Hi! You're not supposed to be here.` indicates that the server is ready to be used. You can now begin [using your new server](https://docs.standardnotes.org/self-hosting/ec2-nginx#using-your-new-server).

**Comment by Jungack** [comment]
> Hey @Jungack, the message `Hi! You're not supposed to be here.` indicates that the server is ready to be used. You can now begin [using your new server](https://docs.standardnotes.org/self-hosting/ec2-nginx#using-your-new-server).

Thanks for reply ! As I have said, I can't register, neither using the self hosted web client, nor the online one on the official site : It is written that the server is unreachable. At least I think there is a problem with the command `rails assets:precompile` as I have said before.

**Comment by johnny243** [comment]
The `rails assets:precompile` command compiles the assets and places the same in the `/assets` directory. The `syncing-server` is an API-based application, thus this is not important to function properly, it is just mentioned in the docs as a usual deployment step.

What is the content of your `.env` file (skip sensitive information)?

**Comment by Jungack** [comment]
> The `rails assets:precompile` command compiles the assets and places the same in the `/assets` directory. The `syncing-server` is an API-based application, thus this is not important to function properly and it should be working for you as-is. This step is mentioned in the docs as a usual deployment step.
> 
> What is the content of your `.env` file (skip sensitive information)?

Hello,
I just managed to make It work thank you ! In fact, I had some problems with the `.env` file you are right ! The page "You are not supposed to be here" still have an ugly layout, but there is not errors in log anymore ! 
The problem was that I misconfigured the MySQL database : there was permission problems with the user that I dedicated for standard notes. But thank you anyway !
