### ISSUE TITLE
[Feature Suggestion] Cold Storage

### ISSUE THREAD

**Issue by yingw787** [standardnotes/syncing-server#38]
Hey @mobitar,

I had a feature suggestion (sadly no pull request though) for the syncing server; would a cold storage option be in the cards in the near future? I have around 750 notes, and it takes a little while in order to sync everything. Most of the notes I archive successfully, but the archive remains synced, and I don't fetch notes from the archive often. It'd be really cool if after 30 days in archive without user access, notes could go into "cold storage" where they are not synced by default, and are only pulled when manually requested and refreshed.

Unfortunately I'm not too familiar with Ruby...and I think this would be a full-stack issue, and since I don't have a pull request, I'm just putting this out there as a possible performance improvement.

Thanks so much! I never thought I'd get to 750 notes with Standard Notes, but I'm here and I'm so happy I made the purchase :)
Ying

**Comment by mobitar** [comment]
Hmm..I'm not sure I follow what you mean. Notes that are untouched do not go back and forth between the server. The initial loading that occurs when you open the app is all local, and happens on your device.

The only time you'd deal with the server for _all_ your notes would be when you first sign in.

**Comment by yingw787** [comment]
At least on iOS, after I open the app and punch in the optional passcode, I see the message "Syncing {100, 200, 300}/750", and then after "Syncing 700/750" it says "Syncing". I checked my desktop application, and I think it might be a unique behavior to iOS since I don't see that exact same message. If in the case on iOS that initial loading is taking place from local persist, could we have the option to load only the notes in current + archive < 30 days?

**Comment by mobitar** [comment]
You sure it says "Syncing 100/750" and not "Decrypting 100/750"?

**Comment by yingw787** [comment]
It might be "decrypting", actually. I don't have my phone on me at the moment, but I wouldn't be at all surprised if decrypting notes kept on local persist would incur a performance overhead. I just didn't want to wait for that period of time and was brainstorming ideas of how it might go faster. I'll go ahead and close this issue.

**Comment by mobitar** [comment]
If you disable Device Storage Encryption from the settings (not recommended; but up to you), you'll see a speed-up here.
