### ISSUE TITLE
Administration-Remove User

### ISSUE THREAD

**Issue by git-noise** [standardnotes/syncing-server#47]
Hello,
I am not too sure if this is the right place, so please feel free to point me somewhere else.
I have installed the sync-server following your documentation, but could not find anywhere if any administration features where available.
As an example, how would one remove an existing user? I found traces of some admin controller in the repo code, and wanted to know if it was possible to get a bit more information on how to actually use it. Is there an API call that can be made?
In the negative, what would be the operation to perform to remove a user?

Many thanks and have a good rest of the day,

Best,

**Comment by johnny243** [comment]
Hello @git-noise,

You can use the `delete_account` method to delete any accounts present it your syncing-server. But before you can use it, you must authenticate your request. 

Currently, the request is authenticated by checking your IP address against a list of Administrator IPs. You can define this in the `ADMIN_IPS` environment variable. Next, you need to pass an "admin key" along with your request. This key should be secret to you and can set it in the `ADMIN_KEY` environment variable.

Then from an authorized IP, you send a `POST` request to `/admin/delete_account`, providing the `email` param for the account you wish to delete, and the `admin_key` param for the one you defined in your environment variable.

Let me know if you need further advice :+1:

**Comment by git-noise** [comment]
Hello @johnny243,

Many thanks for the answer, it works perfectly!
The code is actually pretty clear and I should have figured it out by myself, but may I suggest you maybe add a quick note on the self-hosted documentation?

Have a good one,

Best,
