### ISSUE TITLE
Docker Hub image

### ISSUE THREAD

**Issue by danofun** [standardnotes/syncing-server#48]
I originally posted this on r/StandardNotes where u/sn-jaspal requested I create this enhancement request.

Your Dockerfile is a ready to build. Is there a reason you are not utilizing Docker Hub to auto-compile, build, host, and easily distribute your image? I believe this is ultimately the same request [dslovin](https://github.com/dslovin) is making in issue #14 

[Here](https://docs.docker.com/docker-hub/builds/) are the Docker Hub provided instructions. I have forked/cloned this repository and have it auto-compiling without issue using Docker Hub at danofun/syncing-server. The only change I see to your code would be changing docker-compose.yml line #4 to reflect the new Docker Hub image.
`image: standardnotes/syncing-server`

**Comment by karolsojko** [comment]
Our docker images are now published automatically and can be retrieved from Docker Hub: https://hub.docker.com/repository/docker/standardnotes/syncing-server/general

**Comment by JaspalSuri** [comment]
Hey Dan, I just came across this again and wanted to apologize for letting it slip through the cracks! I hope that everything is working as expected. Please let us know if you have any questions.
