### ISSUE TITLE
An item without a content and content-type

### ISSUE THREAD

**Issue by jonhadfield** [standardnotes/syncing-server#49]
Using my API I seem to have accidentally created an item both without content and without a content type. As you can see by the timestamps this is from last September, so maybe a lack of input validation that's since been fixed?

    (gosn.DecryptedItem) {
     UUID: (string) (len=36) "5f4f0b99-ea6b-4a8d-982e-88ca87dd7932",
     Content: (string) "",
     ContentType: (string) "",
     Deleted: (bool) false,
     CreatedAt: (string) (len=24) "2019-09-22T22:00:53.933Z",
     UpdatedAt: (string) (len=24) "2019-09-22T22:00:53.933Z"
    }

This is an account I used for testing my code in CircleCI and I'm now using a new one so, if it's of interest, please have a look and then delete the account:
email: sn-dotfiles-circleci@lessknown.co.uk
password: xBc4paN9S2nSXw6C

**Comment by jonhadfield** [comment]
As raised on the Slack #help channel, I've got a different error:
![image](https://user-images.githubusercontent.com/843944/82223186-40961b00-991a-11ea-99e6-f09d7ff71655.png)
In the console it shows:
```
Caught sync success exception: TypeError: Cannot read property 'map' of null
    at t.value (app.js:15)
    at t.value (app.js:15)
    at t.<anonymous> (app.js:15)
    at c (app.js:29)
    at Generator._invoke (app.js:29)
    at Generator.forEach.e.<computed> [as next] (app.js:29)
    at c (app.js:29)
    at t (app.js:29)
    at app.js:29
    at new Promise (<anonymous>)
app.js:15 Sync error:  TypeError: Cannot read property 'map' of null
    at t.value (app.js:15)
    at t.value (app.js:15)
    at t.<anonymous> (app.js:15)
    at c (app.js:29)
    at Generator._invoke (app.js:29)
    at Generator.forEach.e.<computed> [as next] (app.js:29)
    at c (app.js:29)
    at t (app.js:29)
    at app.js:29
    at new Promise (<anonymous>)`
```
What may be related is the following content that includes references to items with both missing uuids and content types:

```
{
        "uuid": "8a53fde9-af1b-426f-b68c-e437062a2019",
        "content": {
            "title": "Work",
            "references": [
                {
                    "uuid": "",
                    "content_type": ""
                },
                {
                    "uuid": "",
                    "content_type": ""
                },
                {
                    "uuid": "",
                    "content_type": ""
                },
```

Comment from @mobitar on Slack:

> I’m not sure that the clients are equipped to handle empty string content_types. They are however equipped to handle NULL content_types.

**Comment by jonhadfield** [comment]
I deleted the following and the issue is now syncing completes without any errors.
```
    {
        "uuid": "36aa8a87-cd88-4e2f-9768-e536f0ec62e1",
        "content": {
            "title": "dotfiles.kube",
            "references": null,
            "appData": {
                "org.standardnotes.sn": {
                    "client_updated_at": "2019-12-12T13:34:40.005Z"
                }
            }
        },
        "content_type": "Tag",
        "created_at": "2019-12-12T13:34:40.005Z",
        "updated_at": "2019-12-12T13:34:40.057Z"
    },
    {
        "uuid": "35b96c7a-2f69-4b84-8f31-85f8b8c4165f",
        "content": {
            "title": "Linux",
            "references": null,
            "appData": {
                "org.standardnotes.sn": {
                    "client_updated_at": "2018-11-06T20:57:24.855Z"
                }
            }
        },
        "content_type": "Tag",
        "created_at": "2018-08-29T21:06:15.338Z",
        "updated_at": "2018-12-18T10:11:03.902Z"
    },
```
If I create a new tag I notice that it will always have a reference to a note. Is it possible your code is not handling tags with null references?
Here's a new tag I created to give an example:
 ```
  {
        "uuid": "d40493e5-0b2b-4aeb-912c-745e2861d15f",
        "content": {
            "title": "NEW_TAG",
            "references": [
                {
                    "uuid": "d40753bf-d633-40d0-8854-2bfb78f28ecd",
                    "content_type": "Note"
                }
            ],
            "appData": {
                "org.standardnotes.sn": {
                    "client_updated_at": "1970-01-01T00:00:00.000Z"
                }
            }
        },
        "content_type": "Tag",
        "created_at": "2020-05-18T14:58:26.731Z",
        "updated_at": "2020-05-18T14:58:26.877Z"
    }
```

**Comment by mobitar** [comment]
Correct, references should never be null. Should be empty array instead.

**Comment by mobitar** [comment]
I believe however we will have safer handling here in v3.5, but in the meantime the correct way to go is empty arrays.

**Comment by jonhadfield** [comment]
Will do. Thanks.
