### ISSUE TITLE
Re-Add Docker instructions 

### ISSUE THREAD

**Issue by taaem** [standardnotes/syncing-server#5]
Hello,
The instructions on standardnotes.org, need preconfigured docker-compose and Dockerfiles in the repository, but in this new repo they're not there. 

It would be really appreciated, if these instructions and files could be updated/added, so self-hosted servers can be migrated.

Best Regards.

**Comment by mobitar** [comment]
Development docker integration support has just been added by @mindovermiles262, and I think he has plans for docker-compose support.

**Comment by mindovermiles262** [comment]
Yes I am working on docker-compose support for this syncing-server. Updates coming soon
