### ISSUE TITLE
Reverts back to the default server address-Wrong Credentials

### ISSUE THREAD

**Issue by KouroshMaheri** [standardnotes/syncing-server#54]
I try to add the IMAP note accounts (similar to Apple notes) to the app. The server is Namecheap Private Email (powered by Open-Xchange). https://mail.privateemail.com

But the issue is that on the Standard note app, I can not save the server, and each time it reverts back to the default one. Another issue is I cannot log in to the server at all. It notifies me of the wrong credentials.

**Comment by johnny243** [comment]
Hi @KouroshMaheri, thanks for reaching out!

Could you clarify me what is the "IMAP note accounts" for?

Is it that you are using your own `syncing-server` instance and can not use it?

Thanks!

**Comment by KouroshMaheri** [comment]
Hi, and thanks for your reply. I mean Notes in an IMAP folder the way that Apple uses notes on iOS and Apple devices. I try to use an Open-Xchange server. There is another app for Android for this "Kolab" but it also does not work well.

**Comment by johnny243** [comment]
> I mean Notes in an IMAP folder the way that Apple uses notes on iOS and Apple devices.

Got you :ok_hand:

Standard Notes app can only be used with the `syncing-server` (or any other implementation that supports our encryption protocols). 

If you prefer, you have the option of deploying your own server. See the [self hosting page](https://docs.standardnotes.org/self-hosting/getting-started) to get started.

Let me know if you need anything else, thanks!

**Comment by KouroshMaheri** [comment]
Thanks for the clarifications.
Best,

Kourosh
