### ISSUE TITLE
unable to connect to self hosted backend

### ISSUE THREAD

**Issue by yozamacs** [standardnotes/syncing-server#74]
My syncing server repo is on the master branch but I'm still getting an error about version mismatch. Not sure what else I can do to get it to work.

**Comment by mobitar** [comment]
How did you deploy your server? Docker? And when was your account created? Please see here: https://github.com/standardnotes/syncing-server/issues/68#issuecomment-660105167

**Comment by yozamacs** [comment]
I deployed my server with docker following the exact instruction [here](https://docs.standardnotes.org/self-hosting/docker). And then when I heard that the develop branch was the incorrect branch, I checked out the master branch and restarted my docker containers. Not sure what else I can do. I did use an account that was already created, but this was all last week, the account creation and the server creation.

**Comment by johnny243** [comment]
You will need to re-create your database, because it still has `004` data and schema. In your case it's fine to re-create your database because you are starting out with the `syncing-server`:

1. Stop both `app` and `db` containers: 
```bash
docker stop syncing-server_app_1 syncing-server_db_1
```
1. Remove both `app` and `db` containers: 
```bash
docker rm syncing-server_app_1 syncing-server_db_1
```
1. Remove the `syncing-server_std_notes_db` volume: 
```bash
docker volume rm syncing-server_std_notes_db
```
1. Finally, run `docker-compose up -d` to rebuild containers

**Comment by yozamacs** [comment]
I did all of that and I'm still getting the same error. Do I need to delete the data directory in the syncing server repo as well?

**Comment by johnny243** [comment]
> Do I need to delete the data directory in the syncing server repo as well?

The `data` directory is used in the [docker-compose.yml](https://github.com/standardnotes/syncing-server/blob/55a22251ddc3890275af150513aee759441b9885/docker-compose.yml#L30) file from the `develop` branch only. So if your syncing-server repo is on `master`, that shouldn't matter.

I should've mentioned that before running step 4, you should be in the `master` branch.

**Comment by yozamacs** [comment]
Yep I was on the master branch when I followed all of those steps
  

  
  

  
  
>

**Comment by johnny243** [comment]
Please run the following command and paste output here:

```
docker exec -it syncing-server_app_1 bundle exec rails db:migrate:status
```

**Comment by yozamacs** [comment]
```
I, [2020-07-19T02:45:49.280994 #38]  INFO -- sentry: ** [Raven] Raven 3.0.0 configured not to capture errors: DSN not set

database: standard_notes_db

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20161114004542  Create users
   up     20161114004634  Create items
   up     20170127020603  Expand content column
   up     20170205182304  Add content type index
   up     20170213175749  Migrate dropbox to ext server
   up     20170221011303  Increase item date precision
   up     20170309232850  Change item key to text
   up     20170703185958  Add salts
   up     20170805143503  Add version
   up     20170808194325  Remove pw auth
   up     20171102152234  Add user agent to items
   up     20180125022306  Make exts daily
   up     20180218153714  Add content type index to items
   up     20180506160552  Create extension settings
   up     20180506170854  Make revisions realtime
   up     20190315163954  Add user agent to user
   up     20190525212549  Add lockout to users
   up     20191229224131  Add items key id to items
   up     20200220201723  Add better indexes
   up     20200328222807  Add items deleted index
   up     20200410020904  Create sessions
   up     20200601101128  Add item revisions
   up     20200605085931  Add duplicate of to items
```

**Comment by karolsojko** [comment]
Looking at the migrations list you must have run the migrations from the `develop` branch ( https://github.com/standardnotes/syncing-server/tree/develop/db/migrate ) because last ones are not available in the `master` branch

**Comment by johnny243** [comment]
Just to make sure, run:

```bash
git checkout master
docker-compose build --no-cache
docker-compose up -d
```

**Comment by yozamacs** [comment]
now I'm getting an "invalid email or password" error when I try to sign in

**Comment by johnny243** [comment]
That's fine, your syncing-server is on the correct branch now, meaning that the old database was dropped and a new one was created based on the schema of the `master` branch. You should be able to register your accounts and sign in with no issues.

**Comment by yozamacs** [comment]
do I need to register my account in the syncing server somehow? or do I have to create a new account to use with the syncing server?

**Comment by johnny243** [comment]
> do I have to create a new account to use with the syncing server?

Yes, using the Registration form.

**Comment by yozamacs** [comment]
thanks!!
