### ISSUE TITLE
Alternative command for secret when using docker-compose

### ISSUE THREAD

**Issue by Heziode** [standardnotes/syncing-server#82]
Maybe add another line here:

https://github.com/standardnotes/syncing-server/blob/9b458f9480fd168554e71ef8c5933d170e99f195/env.sample#L28

With something like this:

```yml
# or by using: openssl rand -hex 64
```

For users who have never used RoR (like me) and to prevent to "pollute" the prod server by installing RoR only for generate secrets.

**Comment by JaspalSuri** [comment]
Hi, I've assigned our backend devs to this issue. Thanks for bringing this to our attention!

**Comment by JaspalSuri** [comment]
Let us know if you have any other questions!
