### ISSUE TITLE
CSRF token authenticity warning

### ISSUE THREAD

**Issue by karolsojko** [standardnotes/syncing-server#86]
With every request we are seeing this warning entry in logs:
```
Can't verify CSRF token authenticity.
```

This basically doubles the amount of logs the app produces so we need to either fix the issue or get rid of the message.

**Comment by johnny243** [comment]
Since the `syncing-server` is an API, I think the concept of `CSRF` doesn't apply here.

**Comment by johnny243** [comment]
https://github.com/standardnotes/syncing-server/blob/c3b37f3cd34c418866b827a74065d08508b6a934/app/controllers/application_controller.rb#L1

We can change `ActionController::Base` to `ActionController::API`

**Comment by karolsojko** [comment]
good catch @johnny243 👍
