### ISSUE TITLE
Legal question

### ISSUE THREAD

**Issue by raelb** [standardnotes/syncing-server#9]
Hello,
If I were to develop a server based on the [Standard Notes Spec](https://docs.standardnotes.org/specification/sync), however not using the ruby implementation, but instead my own implementation in a different language, would that be subject to the same AGPL license?

**Comment by mobitar** [comment]
I don't see why it would be, if it's your own code..

**Comment by raelb** [comment]
Ok.

What if I use the current `syncing-server` implementation as a reference or guide to my implementation, such that the end result would not be a direct port of the code to another language, but the logic for certain parts would be borrowed from the ruby implementation?

**Comment by mobitar** [comment]
I'm honestly not sure. Do you want to make a closed-source server implementation?

**Comment by raelb** [comment]
Essentially Yes. I like the simplicity and "dumb" nature of the sync server (i.e. it could be used with almost anything) and that it uses  E2EE. I am not familiar with ruby, and would consider creating my own server, perhaps in C#. The main code I would want to "borrow" is the encryption logic, to make sure I am using a correct implementation, and not my own which may have flaws.

**Comment by mobitar** [comment]
There really is no encryption logic on the backend. It's all handled client side. The server is just dumb storage essentially.

**Comment by raelb** [comment]
Ok, good point. Thanks I'll close for now.
