### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by joekerna** [standardnotes/syncing-server#90]
I've updated to the latest version. When running `docker-compose up -d` I get

> root@nuc:/opt/syncing-server# sudo docker-compose up -d
> syncing-server_db_1 is up-to-date
> Creating syncing-server_app_1 ... error
> 
> ERROR: for syncing-server_app_1  Cannot start service app: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"start-local\": executable file not found in $PATH": unknown
> 
> ERROR: for app  Cannot start service app: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"start-local\": executable file not found in $PATH": unknown
> ERROR: Encountered errors while bringing up the project.
> root@nuc:/opt/syncing-server# 

My .env file is

> \# Sample ENV setup Variables
> \# Copy this file and update as needed.
> \#
> \#   $ cp env.sample .env
> \#
> \# Do not include this new file in source control
> \#
> 
> \# Rails Settings
> EXPOSED_PORT=3001
> RAILS_ENV=development
> RAILS_LOG_TO_STDOUT=false
> \#SQS_QUEUE=somequeue
> \#AWS_REGION=us-west1
> 
> \# Database Settings
> DB_PORT=3306
> DB_HOST=db #=> If using docker-compose
> 
> DB_DATABASE=standard_notes_db
> DB_USERNAME=std_notes_user
> \# Please change this!
> DB_PASSWORD=mysecretpassword
> \# Please change this!
> DB_ROOT_PASSWORD=mysecretpassword
> DB_POOL_SIZE=30
> DB_WAIT_TIMEOUT=180
> 
> \# Secrets
> \# Use: bundle exec rake secret
> \# To generate required secrets below
> \#
> 
> SECRET_KEY_BASE=changeme123
> 
> \# Disable user registration
> \#DISABLE_USER_REGISTRATION=true
> 
> \# Datadog
> DATADOG_ENABLED=false
> 

Can you help me out? The server was working fine before the update

**Comment by joekerna** [comment]
Using `docker-compose up -d --build` fixed the issue.

What is the suggested way to update the syncing-server?

1. git pull
2. docker-compose up -d --build

**Comment by karolsojko** [comment]
@joekerna whenever there is a change in the docker setup and/or dependency files you need to rebuild the image. 

docker-compose is used for local development purposes mainly. If your intention is not contributing but just running the app I recommend using our official image from Docker hub like this:

```
docker run -d -p 3000:3000 --env-file=your-env-file standardnotes/syncing-server:stable
```

Or if you want to use the `develop` branch that is in a work-in-progress state please use:

```
docker run -d -p 3000:3000 --env-file=your-env-file standardnotes/syncing-server:latest
```

**Comment by karolsojko** [comment]
I've updated the `README` to avoid further confusion: https://github.com/standardnotes/syncing-server/commit/5e74c773058a7814a00aaf87447df07b7a81f7da

/cc @mobitar @johnny243

**Comment by joekerna** [comment]
@karolsojko oh great, thanks for the clarification. It was not clear to me from the previous `README`

Thanks a lot

**Comment by joekerna** [comment]
In that case, do I need to run the MySQL server seperately?

**Comment by karolsojko** [comment]
Yes, the containerized MySQL is for development purposes mainly

**Comment by joekerna** [comment]
Do you know if PostgreSQL will also work? I have that running already for other applications. That way I won't have to run MySQL for Standardnotes alone

**Comment by karolsojko** [comment]
Syncing Server is only MySQL compatible at the moment
