### ISSUE TITLE
Unable to deploy to heroku

### ISSUE THREAD

**Issue by nm17** [standardnotes/syncing-server#96]
Link: https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fstandardnotes%2Fsyncing-server&template=https%3A%2F%2Fgithub.com%2Fstandardnotes%2Fsyncing-server

```
-----> Ruby app detected

-----> Installing bundler 2.0.2

-----> Removing BUNDLED WITH version in the Gemfile.lock

-----> Compiling Ruby/Rails

-----> Using Ruby version: ruby-2.6.6

-----> Installing dependencies using bundler 2.0.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       You are trying to install in deployment mode after changing
       your Gemfile. Run `bundle install` elsewhere and add the
       updated Gemfile.lock to version control.
       
       You have deleted from the Gemfile:

       * device_detector
       Bundler Output: You are trying to install in deployment mode after changing
       your Gemfile. Run `bundle install` elsewhere and add the
       updated Gemfile.lock to version control.
       
       You have deleted from the Gemfile:
       * device_detector

 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by johnny243** [comment]
Can you use the one located in the [master branch](https://github.com/standardnotes/syncing-server/tree/master)?

**Comment by nm17** [comment]
@johnny243 Same URL and build log

**Comment by AakashSasikumar** [comment]
I am having the same issue. I tried to clone the repo and push it to heroku, and that seemed to work. But when using the heroku syncing server in the advanced options, it keeps saying `A server error occurred while trying to sign in. Please try again.`. It would be very helpful if this issue were fixed.

**Comment by AakashSasikumar** [comment]
UPDATE: I checked the logs and noticed that it wasn't connecting to the SQL DB. I followed the instructions on [this page](https://docs.standardnotes.org/self-hosting/heroku) and did all the stuff with no issues.

But now the same error persists. Here are the logs,
```
2020-09-29T02:32:36.822810+00:00 app[web.1]: {"level":"FATAL","time":"2020-09-29T02:32:36.822+00:00","message":"  ","ddsource":["ruby"]}

2020-09-29T02:32:36.822970+00:00 app[web.1]: {"level":"FATAL","time":"2020-09-29T02:32:36.822+00:00","message":"TypeError (no implicit conversion of nil into String):","ddsource":["ruby"]}

2020-09-29T02:32:36.823080+00:00 app[web.1]: {"level":"FATAL","time":"2020-09-29T02:32:36.822+00:00","message":"  ","ddsource":["ruby"]}

2020-09-29T02:32:36.823191+00:00 app[web.1]: {"level":"FATAL","time":"2020-09-29T02:32:36.823+00:00","message":"app/controllers/api/auth_controller.rb:256:in `+'\napp/controllers/api/auth_controller.rb:256:in `pseudo_auth_params'\napp/controllers/api/auth_controller.rb:244:in `auth_params'","ddsource":["ruby"]}
```

**Comment by mobitar** [comment]
Make sure you're using the master branch and not the develop branch.

Otherwise if you want to use the develop branch, add a new ENV variable: `PSEUDO_KEY_PARAMS_KEY`. Set its value equal to any secure random string.

**Comment by glamoroussky** [comment]
I got the same result, frustrating

**Comment by flexingtoohardouchie** [comment]
FYI to those who were affected by this issue, like me: **it seems to be fixed**. I was able to spin up an instance successfully.

**Comment by nm17** [comment]
@flexingtoohardouchie can confirm that it's working properly now. Closing this issue.
