### ISSUE TITLE
How to run sync server with nginx under other location

### ISSUE THREAD

**Issue by damien122** [standardnotes/syncing-server#98]
Hi,

I tried to run the sync server with nginx and want to use other location

Snippet from my site config:
```
location /notes/ {
                proxy_pass http://127.0.0.1:3000;
                root /MY/FOLDER/syncing-server/public;
        }
```

But I got every time an error that the POST path "/notes/auth" was not found.
So can I change somewhere in the sync server the default path or should I use a sub domain for the sync server?

**Comment by karolsojko** [comment]
We recommend using our official Docker image as your default setup, like in here: https://github.com/standardnotes/syncing-server#docker-setup

You can then use nginx as a reverse proxy for the running container.

**Comment by damien122** [comment]
And without docker? Is it possible to use locations with nginx for the sync server?

**Comment by karolsojko** [comment]
I think it's a matter of your nginx configuration. Maybe this could help: https://stackoverflow.com/a/33325584 ?

**Comment by damien122** [comment]
Thx, rewrite in the location works fine :)

```
rewrite ^/a/(.*) /$1  break;
```
